# Generated by Django 6.1.1 on 2026-09-17 07:27

import children.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=children.models.child_photo_upload_path)),
                ('communication_type', models.CharField(choices=[('verbal', 'Verbal'), ('limited_verbal', 'Limited Verbal'), ('non_verbal', 'Non-Verbal')], default='verbal', max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('medical_info', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('preferred_language', models.CharField(blank=True, max_length=100)),
                ('show_first_name', models.BooleanField(default=True)),
                ('show_photo', models.BooleanField(default=True)),
                ('show_communication', models.BooleanField(default=True)),
                ('show_allergies', models.BooleanField(default=False)),
                ('show_medical_info', models.BooleanField(default=False)),
                ('show_special_instructions', models.BooleanField(default=True)),
                ('show_preferred_language', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
                'db_table': 'children',
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('aunt_uncle', 'Aunt / Uncle'), ('guardian', 'Guardian'), ('teacher', 'Teacher'), ('doctor', 'Doctor'), ('other', 'Other')], max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='children.child')),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['order'],
            },
        ),
    ]
