# Generated by Django 6.1.1 on 2026-09-17 07:27

import django.db.models.deletion
import tags.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('tag_type', models.CharField(choices=[('nfc_qr_wristband', 'NFC + QR Wristband'), ('qr_sticker', 'QR Sticker'), ('nfc_keychain', 'NFC Keychain'), ('qr_card', 'QR Card')], max_length=30)),
                ('placement', models.CharField(choices=[('wristband', 'Wristband'), ('school_bag', 'School Bag'), ('shoe', 'Shoe'), ('clothing', 'Clothing'), ('id_card', 'ID Card'), ('travel_bag', 'Travel Bag'), ('bicycle', 'Bicycle'), ('lunch_bag', 'Lunch Bag'), ('other', 'Other')], default='wristband', max_length=30)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('generated', 'Generated'), ('activated', 'Activated'), ('active', 'Active'), ('lost', 'Lost'), ('deactivated', 'Deactivated'), ('replaced', 'Replaced')], default='requested', max_length=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to=tags.models.qr_upload_path)),
                ('emergency_url', models.URLField(blank=True)),
                ('nfc_uid', models.CharField(blank=True, help_text='Physical NFC chip UID', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='children.child')),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_consent', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='children.child')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='tags.tag')),
            ],
            options={
                'db_table': 'scan_logs',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('tag_type', models.CharField(choices=[('nfc_qr_wristband', 'NFC + QR Wristband'), ('qr_sticker', 'QR Sticker'), ('nfc_keychain', 'NFC Keychain'), ('qr_card', 'QR Card')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='children.child')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('tag', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='tags.tag')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TagEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('requested', 'Requested'), ('generated', 'Generated'), ('activated', 'Activated'), ('lost', 'Lost'), ('deactivated', 'Deactivated'), ('replaced', 'Replaced')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tags.tag')),
            ],
            options={
                'db_table': 'tag_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
